 FROM golang:1.21 AS build
 LABEL tony tony
 WORKDIR /app
 COPY . .
 RUN go mod download
 RUN CGO_ENABLED=0 go build -o /go/bin/catgpt
 FROM gcr.io/distroless/static-debian12:latest-amd64
 COPY --from=build /go/bin/catgpt /catgpt
 EXPOSE 8080
 CMD ["/catgpt"]
